# Generated by Django 5.1.1 on 2024-10-16 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='app.appcategory'),
        ),
        migrations.AlterField(
            model_name='app',
            name='config_forms',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
