# Generated by Django 5.1.1 on 2024-10-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appcomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcomment',
            name='rating',
            field=models.CharField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='5', max_length=3),
        ),
    ]
