# Generated by Django 5.1.1 on 2024-10-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_appcomment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appcomment',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
