# Generated by Django 5.1.1 on 2024-10-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('cookie', models.TextField(blank=True, default='')),
                ('profile_picture', models.ImageField(upload_to='facebook_account/profile_pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
