# Generated by Django 5.1.1 on 2024-10-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='phone_number',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
