# Generated by Django 5.1.1 on 2024-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0002_alter_facebookaccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
