# Generated by Django 5.1.1 on 2024-10-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0004_facebookaccount_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='_2fa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
