# Generated by Django 5.1.1 on 2024-10-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0005_facebookaccount__2fa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
