# Generated by Django 5.1.1 on 2024-10-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0006_alter_facebookaccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='profile_picture',
            field=models.TextField(blank=True, default='https://bbb.u-pec.fr/assets/default-avatar-12ba46e182bedfae9d6de6c3a414a91b85a2383adff1e06ba4261478c380d3e1.png', null=True),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
