# Generated by Django 5.1.1 on 2024-10-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0007_alter_facebookaccount_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
