# Generated by Django 5.1.1 on 2024-10-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0008_alter_facebookaccount_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='pass_mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='_2fa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ChromeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_path', models.CharField(max_length=255)),
                ('user_agent', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('booknark', models.JSONField(default=list, null=True)),
                ('language', models.CharField(max_length=255)),
                ('fbaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chrome_profiles', to='facebook_account.facebookaccount')),
            ],
        ),
    ]
