# Generated by Django 5.1.1 on 2024-10-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0009_facebookaccount_pass_mail_alter_facebookaccount__2fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
