# Generated by Django 5.1.1 on 2024-10-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0011_facebookaccount_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chromeprofile',
            name='booknark',
        ),
        migrations.RemoveField(
            model_name='chromeprofile',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='chromeprofile',
            name='lite_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chromeprofile',
            name='proxy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chromeprofile',
            name='remove_cache',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chromeprofile',
            name='size',
            field=models.CharField(default='1024x768', max_length=255),
        ),
        migrations.AddField(
            model_name='chromeprofile',
            name='start_url',
            field=models.CharField(default='https://www.facebook.com', max_length=255),
        ),
        migrations.AddField(
            model_name='chromeprofile',
            name='ua',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chromeprofile',
            name='language',
            field=models.CharField(default='Vietnamese-vi', max_length=255),
        ),
        migrations.AlterField(
            model_name='chromeprofile',
            name='profile_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chromeprofile',
            name='version',
            field=models.CharField(default='128', max_length=255),
        ),
    ]
