# Generated by Django 5.1.1 on 2024-10-16 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0012_remove_chromeprofile_booknark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromeprofile',
            name='fbaccount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chrome_profiles', to='facebook_account.facebookaccount'),
        ),
    ]
