# Generated by Django 5.1.1 on 2024-10-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0013_alter_chromeprofile_fbaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chromeprofile',
            old_name='remove_cache',
            new_name='remove_cache_after_run',
        ),
        migrations.AlterField(
            model_name='chromeprofile',
            name='ua',
            field=models.CharField(blank=True, default='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36', max_length=255, null=True),
        ),
    ]
