# Generated by Django 5.1.1 on 2024-10-19 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0015_alter_chromeprofile_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromeprofile',
            name='fbaccount',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chrome_profile', to='facebook_account.facebookaccount'),
        ),
    ]
