# Generated by Django 5.1.1 on 2024-10-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0017_alter_chromeprofile_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookaccount',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
