# Generated by Django 5.1.1 on 2024-10-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0018_facebookaccount_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
