# Generated by Django 5.1.1 on 2024-10-25 16:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_account', '0019_alter_facebookaccount_access_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chromeprofile',
            name='version',
            field=models.CharField(choices=[('128', '128'), ('127', '127'), ('126', '126'), ('125', '125'), ('124', '124'), ('123', '123'), ('122', '122'), ('121', '121'), ('120', '120'), ('119', '119'), ('118', '118'), ('117', '117')], default='128', max_length=255, verbose_name='Phiên bản chrome'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='_2fa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='2FA'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Access Token'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái hoạt động'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='fb_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Cộng tác viên'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='cookie',
            field=models.TextField(blank=True, default='', verbose_name='Cookie'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần đăng nhập cuối'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='pass_mail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mật khẩu email'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Mật khẩu'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='profile_picture',
            field=models.TextField(blank=True, default='https://bbb.u-pec.fr/assets/default-avatar-12ba46e182bedfae9d6de6c3a414a91b85a2383adff1e06ba4261478c380d3e1.png', null=True, verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='uid',
            field=models.CharField(max_length=255, unique=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='facebookaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Lần cập nhật cuối'),
        ),
    ]
