# Generated by Django 5.1.1 on 2024-10-15 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('facebook_account', '0012_remove_chromeprofile_booknark_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('in_progress', 'Đang chạy'), ('pending', 'Đang chờ'), ('done', 'Hoàn thành'), ('failed', 'Lỗi'), ('cancelled', 'Hủy bỏ')], default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_tasks', to='app.app')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_tasks', to=settings.AUTH_USER_MODEL)),
                ('fb_accounts', models.ManyToManyField(related_name='app_tasks', to='facebook_account.facebookaccount')),
            ],
        ),
    ]
