# Generated by Django 5.1.1 on 2024-10-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apptask',
            old_name='author',
            new_name='user',
        ),
    ]
