# Generated by Django 5.1.1 on 2024-10-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_task', '0003_alter_apptask_status_alter_apptask_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptask',
            name='status_text',
            field=models.CharField(blank=True, default='Đang chờ', max_length=255, null=True),
        ),
    ]
